export const ActionTypes = {
  SET_BASE: "SET_BASE",
  SELECTED_BASE: "SELECTED_BASE",
  REMOVE_SELECTED_BASE: "REMOVE_SELECTED_BASE",

  GET_DOCUMENTS: "GET_DOCUMENTS",
  SELECTED_DOCUMENT: "SELECTED_DOCUMENT",
  REMOVE_SELECTED_DOCUMENT: "REMOVE_SELECTED_DOCUMENT",

  SET_SERVICE: "SET_SERVICE",
  SELECTED_SERVICE: "SELECTED_SERVICE",
  REMOVE_SELECTED_SERVICE: "REMOVE_SELECTED_SERVICE",

  SET_CORPS: "SET_CORPS",
  LIST_CORPS: "LIST_CORPS",
  SET_EDIT: "SET_EDIT",
  EDIT_CORPS: "EDIT_CORPS",
  SELECTED_CORPS: "SELECTED_CORPS",
  REMOVE_SELECTED_CORPS: "REMOVE_SELECTED_CORPS",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  LOGOUT: "USERS_LOGOUT",
};
